# Generated by Django 5.0.7 on 2024-08-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
