# Generated by Django 5.0.7 on 2024-08-05 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
