# Generated by Django 5.0.7 on 2024-08-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_task_completed_by_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
